import type { Metadata } from 'next'
import { Inter, Permanent_Marker, Playpen_Sans, Cairo_Play } from 'next/font/google'
import '../globals.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { Providers } from '../providers'

const inter = Inter({ subsets: ['latin'] })

const cairo = Cairo_Play({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-cairo'
})

const playpen = Playpen_Sans({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-playpen'
})

export const metadata: Metadata = {
  title: '<Sadurski/>',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={`${inter.className} ${cairo.variable} ${playpen.variable} font-playpen`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
